### ISSUE TITLE
Tracking issue for the initial implementation

### ISSUE THREAD

**Issue by fjarri** [entropyxyz/synedrion#1]
(Figure and section numbers correspond to the reference paper https://eprint.iacr.org/2021/060)

The 6-round protocol was moved to a separate issue (#36).

Main protocols:
- [x] Figure 3: Threshold ECDSA: Online Signing (includes Figs. 5, 6, 7, 8)
- [x] Figure 4: Threshold ECDSA: Non-Interactive Signing (includes Figs. 5, 6, 7, 8)

Preliminary steps:
- [x] Figure 5: ECDSA Key-Generation (includes `Π^{sch}`)
- [x] Figure 6: Auxiliary Info. & Key Refresh in Three Rounds (includes `Π^{sch}`, `Π^{prm}`, `П^{fac}`, `Π^{mod}`)

3-round signing:
- [x] Figure 7: ECDSA Pre-Signing (includes `Π^{enc}`, `Π^{aff-g}`, `Π^{log*}`, `Π^{mul}`, `Π^{dec}`)
- [x] Figure 8: ECDSA Signing (includes `Π^{aff-g}`, `Π^{mul*}`, `Π^{dec}`)

Sigma-protocols:
- [x] Figure 14: Paillier Encryption in Range ZK – `Π^{enc}` (#17)
- [x] Figure 15: Paillier Affine Operation with Group Commitment in Range ZK – `Π^{aff-g}` (#16)
- [x] Figure 16: Paillier-Blum Modulus ZK – `Π^{mod}`
- [x] Figure 17: Ring-Pedersen Parameters ZK – `Π^{prm}`
- [x] Figure 22: Schnorr PoK – `Π^{sch}`
- [x] Figure 25: Knowledge of Exponent vs Paillier Encryption – `Π^{log*}` (#18)
- [x] Figure 28: No Small Factor Proof - `П^{fac}` (#19)
- [x] Figure 29: Paillier Multiplication – `Π^{mul}` (#23)
- [x] Figure 30: Paillier Decryption modulo `q` – `Π^{dec}` (#24)
- [x] Figure 31: Multiplication Paillier vs Group – `Π^{mul*}` (#25)
